definitions:
  config:
    /hippo:configuration/hippo:domains/frontendconfig/frontend-plugins/exclude-updater:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: false
      hipposys:facet: plugin.class
      hipposys:filter: false
      hipposys:type: String
      hipposys:value: org.hippoecm.frontend.plugins.cms.admin.updater.UpdaterPanelPlugin
    /hippo:configuration/hippo:domains/frontendconfig/frontend-plugins/exclude-system-properties:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: false
      hipposys:facet: plugin.class
      hipposys:filter: false
      hipposys:type: String
      hipposys:value: org.hippoecm.frontend.plugins.cms.admin.system.SystemPropertiesPlugin
    /hippo:configuration/hippo:domains/frontendconfig/frontend-plugins/exclude-system-info:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: false
      hipposys:facet: plugin.class
      hipposys:filter: false
      hipposys:type: String
      hipposys:value: org.hippoecm.frontend.plugins.cms.admin.system.SystemInfoPlugin
    /hippo:configuration/hippo:domains/frontendconfig/frontend-plugins/exclude-permissions:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: false
      hipposys:facet: plugin.class
      hipposys:filter: false
      hipposys:type: String
      hipposys:value: org.hippoecm.frontend.plugins.cms.admin.permissions.PermissionsPlugin
    /hippo:configuration/hippo:domains/frontendconfig/frontend-plugins/exclude-groups:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: false
      hipposys:facet: plugin.class
      hipposys:filter: false
      hipposys:type: String
      hipposys:value: org.hippoecm.frontend.plugins.cms.admin.groups.ListGroupsPlugin
