definitions:
  config:
    /hst:hst/hst:configurations/mygov:
      jcr:primaryType: hst:configuration
      hst:inheritsfrom: [../common]
      /hst:abstractpages:
        jcr:primaryType: hst:pages
      /hst:catalog:
        jcr:primaryType: hst:catalog
        /mygov-catalog:
          jcr:primaryType: hst:containeritempackage
      /hst:components:
        jcr:primaryType: hst:components
      /hst:pages:
        jcr:primaryType: hst:pages
      /hst:prototypepages:
        jcr:primaryType: hst:pages
      /hst:sitemap:
        jcr:primaryType: hst:sitemap
        /organisations:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/organisationlist
          hst:relativecontentpath: organisations/index
          /_default_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/organisation
            hst:relativecontentpath: organisations/${1}
      /hst:sitemenus:
        jcr:primaryType: hst:sitemenus
      /hst:templates:
        jcr:primaryType: hst:templates
        /home-main:
          jcr:primaryType: hst:template
          hst:renderpath: webfile:/freemarker/mygov/home-main.ftl
      /hst:workspace:
        jcr:primaryType: hst:workspace
        /hst:channel:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:channel
          hst:name: Mygov
          hst:type: website
          hst:channelinfoclass: scot.mygov.publishing.channels.WebsiteInfo
        /hst:containers:
          jcr:primaryType: hst:containercomponentfolder
        /hst:pages:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:pages
        /hst:sitemap:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:sitemap
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
