definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
          /root:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/home
            hst:relativecontentpath: index
            hst:refId: root
          /sitemap.xml:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:components/sitemap
          /robots.txt:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/robotstxt
            hst:hiddeninchannelmanager: true
            hst:relativecontentpath: administration/robots
          /_default_:
            jcr:primaryType: hst:sitemapitem
            hst:relativecontentpath: ${1}
            hst:sitemapitemhandlerids: [trailing-slash]
            hst:componentconfigurationmappingvalues: ['hst:pages/article', 'hst:pages/guidepage',
              'hst:pages/organisation']
            hst:componentconfigurationmappingnames: ['publishing:article', 'publishing:guidepage',
              'publishing:organisation']
            /_index_:
              jcr:primaryType: hst:sitemapitem
              hst:relativecontentpath: ${parent}/index
              hst:sitemapitemhandlerids: [trailing-slash]
              hst:componentconfigurationmappingvalues: ['hst:pages/category', 'hst:pages/guide',
                'hst:pages/organisationlist']
              hst:componentconfigurationmappingnames: ['publishing:category', 'publishing:guide',
                'publishing:organisationlist']
            /_default_:
              jcr:primaryType: hst:sitemapitem
              hst:relativecontentpath: ${parent}/${2}
              hst:sitemapitemhandlerids: [trailing-slash]
              hst:componentconfigurationmappingvalues: ['hst:pages/article', 'hst:pages/guidepage',
                'hst:pages/organisation']
              hst:componentconfigurationmappingnames: ['publishing:article', 'publishing:guidepage',
                'publishing:organisation']
              /_default_:
                jcr:primaryType: hst:sitemapitem
                hst:relativecontentpath: ${parent}/${3}
                hst:sitemapitemhandlerids: [trailing-slash]
                hst:componentconfigurationmappingvalues: ['hst:pages/article', 'hst:pages/guidepage',
                  'hst:pages/organisation']
                hst:componentconfigurationmappingnames: ['publishing:article', 'publishing:guidepage',
                  'publishing:organisation']
                /_default_:
                  jcr:primaryType: hst:sitemapitem
                  hst:relativecontentpath: ${parent}/${4}
                  hst:sitemapitemhandlerids: [trailing-slash]
                  hst:componentconfigurationmappingvalues: ['hst:pages/article', 'hst:pages/guidepage',
                    'hst:pages/organisation']
                  hst:componentconfigurationmappingnames: ['publishing:article', 'publishing:guidepage',
                    'publishing:organisation']
                  /_default_:
                    jcr:primaryType: hst:sitemapitem
                    hst:relativecontentpath: ${parent}/${5}
                    hst:sitemapitemhandlerids: [trailing-slash]
                    hst:componentconfigurationmappingvalues: ['hst:pages/article',
                      'hst:pages/guidepage', 'hst:pages/organisationpage']
                    hst:componentconfigurationmappingnames: ['publishing:article',
                      'publishing:guidepage', 'publishing:organisation']
                    /_default_:
                      jcr:primaryType: hst:sitemapitem
                      hst:relativecontentpath: ${parent}/${6}
                      hst:sitemapitemhandlerids: [trailing-slash]
                      hst:componentconfigurationmappingvalues: ['hst:pages/article',
                        'hst:pages/guidepage', 'hst:pages/organisationpage']
                      hst:componentconfigurationmappingnames: ['publishing:article',
                        'publishing:guidepage', 'publishing:organisation']
                      /_default_:
                        jcr:primaryType: hst:sitemapitem
                        hst:relativecontentpath: ${parent}/${7}
                        hst:sitemapitemhandlerids: [trailing-slash]
                        hst:componentconfigurationmappingvalues: ['hst:pages/article',
                          'hst:pages/guidepage', 'hst:pages/organisationpage']
                        hst:componentconfigurationmappingnames: ['publishing:article',
                          'publishing:guidepage', 'publishing:organisation']
                        /_default_:
                          jcr:primaryType: hst:sitemapitem
                          hst:relativecontentpath: ${parent}/${8}
                          hst:sitemapitemhandlerids: [trailing-slash]
                          hst:componentconfigurationmappingvalues: ['hst:pages/article',
                            'hst:pages/guidepage', 'hst:pages/organisationpage']
                          hst:componentconfigurationmappingnames: ['publishing:article',
                            'publishing:guidepage', 'publishing:organisation']
                          /_default_:
                            jcr:primaryType: hst:sitemapitem
                            hst:relativecontentpath: ${parent}/${9}
                            hst:sitemapitemhandlerids: [trailing-slash]
                            hst:componentconfigurationmappingvalues: ['hst:pages/article',
                              'hst:pages/guidepage', 'hst:pages/organisationpage']
                            hst:componentconfigurationmappingnames: ['publishing:article',
                              'publishing:guidepage', 'publishing:organisation']
                            /_default_:
                              jcr:primaryType: hst:sitemapitem
                              hst:relativecontentpath: ${parent}/${10}
                              hst:sitemapitemhandlerids: [trailing-slash]
                              hst:componentconfigurationmappingvalues: ['hst:pages/article',
                                'hst:pages/guidepage', 'hst:pages/organisationpage']
                              hst:componentconfigurationmappingnames: ['publishing:article',
                                'publishing:guidepage', 'publishing:organisation']
                              /_default_:
                                jcr:primaryType: hst:sitemapitem
                                hst:relativecontentpath: ${parent}/${11}
                                hst:sitemapitemhandlerids: [trailing-slash]
                                hst:componentconfigurationmappingvalues: ['hst:pages/article',
                                  'hst:pages/guidepage', 'hst:pages/organisationpage']
                                hst:componentconfigurationmappingnames: ['publishing:article',
                                  'publishing:guidepage', 'publishing:organisation']
                                /_index_:
                                  jcr:primaryType: hst:sitemapitem
                                  hst:relativecontentpath: ${parent}/index
                                  hst:sitemapitemhandlerids: [trailing-slash]
                                  hst:componentconfigurationmappingvalues: ['hst:pages/category',
                                    'hst:pages/guide']
                                  hst:componentconfigurationmappingnames: ['publishing:category',
                                    'publishing:guide']
                              /_index_:
                                jcr:primaryType: hst:sitemapitem
                                hst:relativecontentpath: ${parent}/index
                                hst:sitemapitemhandlerids: [trailing-slash]
                                hst:componentconfigurationmappingvalues: ['hst:pages/category',
                                  'hst:pages/guide']
                                hst:componentconfigurationmappingnames: ['publishing:category',
                                  'publishing:guide']
                            /_index_:
                              jcr:primaryType: hst:sitemapitem
                              hst:relativecontentpath: ${parent}/index
                              hst:sitemapitemhandlerids: [trailing-slash]
                              hst:componentconfigurationmappingvalues: ['hst:pages/category',
                                'hst:pages/guide']
                              hst:componentconfigurationmappingnames: ['publishing:category',
                                'publishing:guide']
                          /_index_:
                            jcr:primaryType: hst:sitemapitem
                            hst:relativecontentpath: ${parent}/index
                            hst:sitemapitemhandlerids: [trailing-slash]
                            hst:componentconfigurationmappingvalues: ['hst:pages/category',
                              'hst:pages/guide']
                            hst:componentconfigurationmappingnames: ['publishing:category',
                              'publishing:guide']
                        /_index_:
                          jcr:primaryType: hst:sitemapitem
                          hst:relativecontentpath: ${parent}/index
                          hst:sitemapitemhandlerids: [trailing-slash]
                          hst:componentconfigurationmappingvalues: ['hst:pages/category',
                            'hst:pages/guide']
                          hst:componentconfigurationmappingnames: ['publishing:category',
                            'publishing:guide']
                      /_index_:
                        jcr:primaryType: hst:sitemapitem
                        hst:relativecontentpath: ${parent}/index
                        hst:sitemapitemhandlerids: [trailing-slash]
                        hst:componentconfigurationmappingvalues: ['hst:pages/category',
                          'hst:pages/guide']
                        hst:componentconfigurationmappingnames: ['publishing:category',
                          'publishing:guide']
                    /_index_:
                      jcr:primaryType: hst:sitemapitem
                      hst:relativecontentpath: ${parent}/index
                      hst:sitemapitemhandlerids: [trailing-slash]
                      hst:componentconfigurationmappingvalues: ['hst:pages/category',
                        'hst:pages/guide']
                      hst:componentconfigurationmappingnames: ['publishing:category',
                        'publishing:guide']
                  /_index_:
                    jcr:primaryType: hst:sitemapitem
                    hst:relativecontentpath: ${parent}/index
                    hst:sitemapitemhandlerids: [trailing-slash]
                    hst:componentconfigurationmappingvalues: ['hst:pages/category',
                      'hst:pages/guide']
                    hst:componentconfigurationmappingnames: ['publishing:category',
                      'publishing:guide']
                /_index_:
                  jcr:primaryType: hst:sitemapitem
                  hst:relativecontentpath: ${parent}/index
                  hst:sitemapitemhandlerids: [trailing-slash]
                  hst:componentconfigurationmappingvalues: ['hst:pages/category',
                    'hst:pages/guide']
                  hst:componentconfigurationmappingnames: ['publishing:category',
                    'publishing:guide']
              /_index_:
                jcr:primaryType: hst:sitemapitem
                hst:componentconfigurationmappingnames: ['publishing:category', 'publishing:guide']
                hst:componentconfigurationmappingvalues: ['hst:pages/category', 'hst:pages/guide']
                hst:relativecontentpath: ${parent}/index
                hst:sitemapitemhandlerids: [trailing-slash]
          /pagenotfound:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:refId: pagenotfound
          /site-furniture:
            jcr:primaryType: hst:sitemapitem
            /footer:
              jcr:primaryType: hst:sitemapitem
              /cookies:
                jcr:primaryType: hst:sitemapitem
                hst:componentconfigurationid: hst:pages/cookiepreferences
                hst:refId: cookies
                hst:relativecontentpath: site-furniture/footer/cookies
                hst:sitemapitemhandlerids: [trailing-slash]
              /_default_:
                jcr:primaryType: hst:sitemapitem
                hst:componentconfigurationid: hst:pages/article
                hst:relativecontentpath: site-furniture/footer/${1}
                hst:sitemapitemhandlerids: [trailing-slash]
          /_any_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:relativecontentpath: '404'
          /search:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/search
            hst:relativecontentpath: search
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/base-layout.ftl
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/base-footer.ftl
          /base-notifications:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/base-notifications.ftl
          /base-siteheader:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/base-siteheader.ftl
          /article-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/article-main.ftl
          /breadcrumbs:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/breadcrumbs.ftl
          /category-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/category-main.ftl
          /home-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/home-main.ftl
          /sitemap.ftl:
            jcr:primaryType: hst:template
            hst:script: '<#ftl attributes={"content_type": "application/xml"} />${sitemap}'
          /robotstxt.ftl:
            jcr:primaryType: hst:template
            hst:script: "<#ftl encoding=\"UTF-8\" strip_whitespace=true  attributes={\"\
              content_type\": \"text/plain\"}>\r\n<#assign hst=JspTaglibs[\"http://www.hippoecm.org/jsp/hst/core\"\
              ] >\r\n<#if document??>\r\n  <#if document.sections??>\r\n    <#list\
              \ document.sections as section>\r\n      <#if section.userAgent?? &&\
              \ (section.disallows?? || disallowedFacNavLinks??)>\r\nUser-agent: ${section.userAgent}\r\
              \n        <#if section.disallows??>\r\n          <#list section.disallows\
              \ as path>\r\nDisallow: ${path}\r\n          </#list>\r\n        </#if>\r\
              \n        <#if disallowedFacNavLinks??>\r\n          <#list disallowedFacNavLinks\
              \ as facnav>\r\nDisallow: <@hst.link link=facnav/>/\r\n          </#list>\r\
              \n        </#if>\r\n      </#if>\r\n    </#list>\r\n  </#if>\r\n  <#if\
              \ document.sitemaps??>\r\n    <#list document.sitemaps as sitemap>\r\
              \nSitemap: ${sitemap}\r\n    </#list>\r\n  </#if>\r\n</#if>"
          /base-googletagmanager:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/gtm.ftl
          /base-styling:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/styling.ftl
          /cookiepreferences-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/cookie-preferences-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/pagenotfound-main.ftl
          /guide-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/guide-main.ftl
          /organisation-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/organisation-main.ftl
          /organisationlist-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/organisationlist-main.ftl
          /notification-banner:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/notification-banner.ftl
          /search-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/common/search-main.ftl
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
          /trailing-slash:
            jcr:primaryType: hst:sitemapitemhandler
            hst:sitemapitemhandlerclassname: scot.mygov.publishing.sitemap.TrailingSlashRedirect
        /hst:catalog:
          jcr:primaryType: hst:catalog
      /publishing:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
