definitions:
  config:
    /hst:hst/hst:hosts:
      /dev-localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhostgroup
        hst:defaultport: 8080
        /localhost:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:virtualhost
          /hst:root:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:homepage: root
            hst:mountpoint: /hst:publishing/hst:sites/publishing
            hst:nochannelinfo: true
            /trading-nation:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:mount
              hst:mountpoint: /hst:publishing/hst:sites/trading-nation
              publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
      /lcl:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /lcl:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
      /dev:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /dev:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
      /int:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /int:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
      /exp:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /exp:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
      /uat:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /uat:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
      /per:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /per:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
      /tst:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /tst:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
      /blu:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /blu:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/live
      /grn:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /grn:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/live
      /live:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /live:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/live
      /origin:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /origin:
                jcr:primaryType: hst:virtualhost
                /hst:root:
                  jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                  hst:schemeagnostic: true
                  publishing:gtm: /content/documents/trading-nation/administration/analytics/live
      /production:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
            /tradingnation:
              jcr:primaryType: hst:virtualhost
              /hst:root:
                jcr:primaryType: hst:mount
                hst:mountpoint: /hst:publishing/hst:sites/trading-nation
                hst:schemeagnostic: true
                publishing:gtm: /content/documents/trading-nation/administration/analytics/live
